# Generated by Django 6.0.1 on 2026-02-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
